routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\WelcomeController;
use App\Http\Middleware\JWTValidation;
use App\Http\Middleware\UserAuthorizationValidation;
use App\Http\Modules\Auth\AuthController;
use App\Http\Modules\Authors\AuthorsController;
use App\Http\Modules\Basket\BasketController;
use App\Http\Modules\Files\FilesController;
use App\Http\Modules\Genres\GenresController;
use App\Http\Modules\News\NewsController;
use App\Http\Modules\Orders\OrdersController;
use App\Http\Modules\Products\ProductsController;
use App\Http\Modules\Publishers\PublishersController;
use App\Http\Modules\Roles\RolesController;
use App\Http\Modules\Users\UsersController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->group(function () {
    Route::get('/', function () {
       if (Auth::check()) {
           return redirect()->route('profile.edit');
       } else {
           return redirect()->route('login');
       }
    });
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->middleware(['auth', 'verified'])->name('dashboard');

    Route::middleware('auth')->group(function () {
        Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
        Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

        Route::resource('roles', RolesController::class);

        Route::resource('users', UsersController::class);
        Route::patch('/users/{id}/recovery', [UsersController::class, 'recovery'])->name('users.recovery');

        Route::resource('authors', AuthorsController::class);
        Route::patch('/authors/{id}/recovery', [AuthorsController::class, 'recovery'])->name('authors.recovery');

        Route::resource('genres', GenresController::class);
        Route::patch('/genres/{id}/recovery', [GenresController::class, 'recovery'])->name('genres.recovery');

        Route::resource('publishers', PublishersController::class);
        Route::patch('/publishers/{id}/recovery', [PublishersController::class, 'recovery'])->name('publishers.recovery');

        Route::resource('orders', OrdersController::class);
        Route::patch('/orders/{id}/recovery', [OrdersController::class, 'recovery'])->whereNumber('id')->name('orders.recovery');
        Route::post('/orders/{id}/repeat', [OrdersController::class, 'repeat'])->whereNumber('id')->name('orders.repeat');
        Route::post('/orders/{id}/cancel', [OrdersController::class, 'cancel'])->whereNumber('id')->name('orders.cancel');

        Route::resource('files', FilesController::class);
        Route::patch('/files/{id}/recovery', [FilesController::class, 'recovery'])->name('files.recovery');
        // PRODUCTS
        Route::get('/products', [ProductsController::class, 'adminIndex'])->name('products.admin.index');
        Route::get('/products/{id}', [ProductsController::class, 'adminShow'])->whereNumber('id')->name('products.admin.show');
        Route::get('/products/{id}/edit', [ProductsController::class, 'adminEdit'])->whereNumber('id')->name('products.admin.edit');
        Route::get('/products/create', [ProductsController::class, 'adminCreate'])->name('products.admin.create');
        Route::post('/products', [ProductsController::class, 'adminStore'])->name('products.admin.store');
        Route::patch('/products/{id}', [ProductsController::class, 'adminUpdate'])->whereNumber('id')->name('products.admin.update');
        Route::delete('/products/{id}', [ProductsController::class, 'adminDestroy'])->whereNumber('id')->name('products.admin.destroy');
        Route::patch('/products/{id}/recovery', [ProductsController::class, 'adminRecovery'])->whereNumber('id')->name('products.admin.recovery');
        // NEWS
        Route::get('/news', [NewsController::class, 'adminIndex'])->name('news.admin.index');
        Route::get('/news/{id}', [NewsController::class, 'adminShow'])->whereNumber('id')->name('news.admin.show');
        Route::get('/news/{id}/edit', [NewsController::class, 'adminEdit'])->whereNumber('id')->name('news.admin.edit');
        Route::get('/news/create', [NewsController::class, 'adminCreate'])->name('news.admin.create');
        Route::post('/news', [NewsController::class, 'adminStore'])->name('news.admin.store');
        Route::patch('/news/{id}', [NewsController::class, 'adminUpdate'])->whereNumber('id')->name('news.admin.update');
        Route::delete('/news/{id}', [NewsController::class, 'adminDestroy'])->whereNumber('id')->name('news.admin.destroy');
        Route::patch('/news/{id}/recovery', [NewsController::class, 'adminRecovery'])->whereNumber('id')->name('news.admin.recovery');
    });

    require __DIR__.'/auth.php';
});

Route::prefix('api')->group(function () {
    Route::post('/login', [AuthController::class, 'login']);
    Route::post('/registration', [AuthController::class, 'registration']);
    Route::middleware([
        JWTValidation::class,
        UserAuthorizationValidation::class
    ])->group(function () {
        Route::get('/user', [AuthController::class, 'getCurrentUser']);
        Route::post('/logout', [AuthController::class, 'logout']);
        Route::post('/news', [NewsController::class, 'store']);
        Route::patch('/news/{id}', [NewsController::class, 'update'])->whereNumber('id');
        Route::delete('/news/{id}', [NewsController::class, 'destroy'])->whereNumber('id');
        Route::post('/news/{id}/recovery', [NewsController::class, 'recovery'])->name('news.recovery');
        Route::post('/products', [ProductsController::class, 'store']);
        Route::patch('/products/{id}', [ProductsController::class, 'update'])->whereNumber('id');
        Route::delete('/products/{id}', [ProductsController::class, 'destroy'])->whereNumber('id');
        Route::post('/products/{id}/recovery', [ProductsController::class, 'recovery']);
        Route::get('/basket', [BasketController::class, 'index'])->name('basket.index');
        Route::post('/products/{id}/basket', [BasketController::class, 'store'])->whereNumber('id')->name('basket.store');
        Route::patch('/basket', [BasketController::class, 'update'])->name('basket.update');
        Route::post('/basket/order', [OrdersController::class, 'storeByBasket']);
    });
    Route::get('/welcome', [WelcomeController::class, 'index']);
    Route::get('/products', [ProductsController::class, 'index']);
    Route::get('/products/{id}', [ProductsController::class, 'show'])->whereNumber('id');
    Route::get('/news', [NewsController::class, 'index']);
    Route::get('/news/{id}', [NewsController::class, 'show'])->whereNumber('id');
    Route::get('/autocomplete/authors', [AuthorsController::class, 'autocomplete']);
    Route::get('/autocomplete/genres', [GenresController::class, 'autocomplete']);
    Route::get('/autocomplete/publishers', [PublishersController::class, 'autocomplete']);
    Route::get('/autocomplete/users', [UsersController::class, 'autocomplete']);
});

app/Models/Users/User.php
<?php

namespace App\Models\Users;

use App\Models\Basket;
use App\Traits\HistoryModelTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Collection;
use Panoscape\History\HasHistories;
use Panoscape\History\HasOperations;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasOperations, HasHistories, HasRoles, HistoryModelTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'is_active',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

    public function basket(): HasMany
    {
        return $this->hasMany(Basket::class, 'owner_id', 'id');
    }


    public static function autocomplete(): Collection
    {
        $result = collect([
            (object)[
                'value' => '',
                'label' => __('datatable.no_selected'),
                'status' => 1
            ]
        ]);

        return $result->merge(
            self::query()
                ->select('id as value', 'name as label', 'is_active')
                ->where('is_active', '=', 1)
                ->orderBy('name')
                ->get()
        );
    }

    public static function frontAutocomplete(): Collection
    {
        return self::query()
            ->select('id as value', 'name as label', 'is_active')
            ->where('is_active', '=', 1)
            ->orderBy('name')
            ->get();
    }

    public function getModelLabel()
    {
        return $this->name;
    }

    public function historyMetaFields(): array
    {
        return [
            'name' => [
                'name' => 'ФИО',
            ],
            'email' => [
                'name' => 'Адрес электронной почты',
            ],
            'email_verified_at' => [
                'name' => 'Верификация почты',
            ],
            'password' => [
                'name' => 'Пароль'
            ],
            'is_active' => [
                'name' => 'Активный'
            ],
        ];
    }
}

app/Models/Users/UsersAuthorization.php
<?php

namespace App\Models\Users;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class UsersAuthorization extends Model
{
    use HasFactory;
    protected $table = 'users_authorization';
    public $timestamps = false;
    protected $guarded = [];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public static function activeSession(int $userID, string $token)
    {
        return self::select('*')->where('user_id', '=', $userID)
            ->where('token', '=', $token)
            ->first();
    }
}

app/Models/Users/UsersAuthorizationLog.php
<?php

namespace App\Models\Users;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UsersAuthorizationLog extends Model
{
    use HasFactory;

    protected $table = 'users_authorization_logs';
    protected $guarded = [];
    public $timestamps = false;
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/users/create.blade.php
<x-app-layout>

    <x-slot name="header">
        <div class="mb-5">
            <div class="float-left">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight ">{{ __('users.headers.create') }}</h2>
            </div>
            <div class="float-right">
                <x-a href="{{ route('users.index') }}">{{ __('actions.back') }}</x-a>
            </div>
        </div>
    </x-slot>

@if (count($errors) > 0)
  <div class="w-full px-10 py-5 bg-red-700">
      <strong>{{ __('validation.whoops') }}</strong>
    <ul>
       @foreach ($errors->all() as $error)
         <li>{{ $error }}</li>
       @endforeach
    </ul>
  </div>
@endif
<x-template.user-role clone="1" :roles="$roles"></x-template.user-role>
<form action="{{route('users.store')}}" method="POST">
    @csrf
    <div class="flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100">
        <div class="w-full sm:max-w-md mt-6 px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg">
            <div class="mt-4">
                <x-input-label for="name" :value="__('users.fields.name')" />
                <x-text-input id="name" name="name" type="text" class="mt-1 block w-full" required autofocus autocomplete="name" />
                <x-input-error class="mt-2" :messages="$errors->get('name')" />
            </div>
            <div class="mt-4">
                <x-label for="email" :value="__('users.fields.email')" />
                <x-input id="email" class="block mt-1 w-full" type="email" name="email" required :placeholder="__('users.fields.email')"/>
            </div>
            <div class="mt-4">
                <x-label for="password" :value="__('users.fields.password')" />
                <x-input id="password" class="block mt-1 w-full"
                         type="password"
                         name="password"
                         required autocomplete="new-password"
                         :placeholder="__('users.fields.password')"/>
            </div>
            <div class="mt-4">
                <x-label for="password_confirmation" :value="__('users.fields.confirm_password')" />
                <x-input id="password_confirmation" class="block mt-1 w-full"
                         type="password"
                         name="password_confirmation" required
                         :placeholder="__('users.fields.confirm_password')"/>
            </div>
            <div class="mt-4">
                <h1 class="font-semibold text-xl text-gray-800 leading-tight">{{ __('roles.headers.title') }}</h1>
                <div class="py-4 flex flex-col container-line-UserRole">
                    <x-template.user-role :roles="$roles"></x-template.user-role>
                </div>
            </div>
            <div class="flex items-center justify-center mt-4">
                <x-btn type="submit">
                    {{ __('actions.submit') }}
                </x-btn>
            </div>
        </div>
    </div>
</form>
</x-app-layout>
<script src="{{asset('js/templates/UserRoleTemplate.js')}}"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        new UserRoleTemplate();
    })
</script>

resources/views/users/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="mb-5">
            <div class="float-left">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight ">{{ __('users.headers.edit') }}</h2>
            </div>
            <div class="float-right">
                <x-a href="{{ route('users.index') }}">{{ __('actions.back') }}</x-a>
            </div>
        </div>
    </x-slot>
    @if (count($errors) > 0)
        <div class="w-full px-10 py-5 bg-red-700">
            <strong>{{ __('validation.whoops') }}</strong>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <x-template.user-role clone="1" :roles="$roles"></x-template.user-role>
    <form action="{{ route('users.update', $user->id) }}" method="POST">
        @csrf
        @method('PATCH')
        <div class="flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100">
            <div class="w-full sm:max-w-md mt-6 px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg">
                <div>
                    <x-input-label for="name" :value="__('users.fields.name')" />
                    <x-text-input id="name" name="name" type="text" class="mt-1 block w-full" :value="old('name', $user->name)" required autofocus autocomplete="name" />
                    <x-input-error class="mt-2" :messages="$errors->get('name')" />
                </div>
                <div class="mt-4">
                    <x-label for="email" :value="__('users.fields.email')" />
                    <x-input id="email" class="block mt-1 w-full" type="email" name="email" :value="old('email', $user->email)" required :placeholder="__('users.fields.email')"/>
                    <x-input-error class="mt-2" :messages="$errors->get('email')" />
                </div>
                <div>
                    <x-input-label for="password" :value="__('users.fields.password')" />
                    <x-text-input id="password" name="password" type="password" class="mt-1 block w-full" autocomplete="new-password" />
                    <x-input-error :messages="$errors->updatePassword->get('password')" class="mt-2" />
                </div>
                <div>
                    <x-input-label for="password_confirmation" :value="__('users.fields.confirm_password')" />
                    <x-text-input id="password_confirmation" name="password_confirmation" type="password" class="mt-1 block w-full" autocomplete="new-password" />
                    <x-input-error :messages="$errors->updatePassword->get('password_confirmation')" class="mt-2" />
                </div>
                <div class="mt-4">
                    <h1 class="font-semibold text-xl text-gray-800 leading-tight">{{ __('roles.headers.title') }}</h1>
                    <div class="py-4 flex flex-col justify-items-stretch container-line-UserRole">
                        @if($userRole->isNotEmpty())
                            @foreach($userRole as $key => $role)
                                <x-template.user-role :type="$key" :fieldID="$role" :roles="$roles"></x-template.user-role>
                            @endforeach
                        @else
                            <x-template.user-role :roles="$roles"></x-template.user-role>
                        @endif
                    </div>
                </div>
                <div class="flex items-center justify-center mt-4">
                    <x-btn type="submit">
                        {{ __('actions.submit') }}
                    </x-btn>
                </div>
            </div>
        </div>

    </form>
</x-app-layout>
<script src="{{asset('js/templates/UserRoleTemplate.js')}}"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        new UserRoleTemplate();
    })
</script>

resources/views/users/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="mb-5">
            <div class="float-left">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight ">{{__('users.headers.title')}}</h2>
            </div>
            <div class="float-right">
                @can('users_edit')
                    <x-a
                        body="success"
                        href="{{ route('users.create') }}"
                    >{{__('users.headers.create')}}
                    </x-a>
                @endcan
            </div>
        </div>
    </x-slot>
    @if ($message = Session::get('success'))
        <div class="w-full px-10 py-5 bg-green-500">
            <p>{{ $message }}</p>
        </div>
    @endif
    <div class="container mx-auto px-4 my-5">
        <form method="GET" action="{{route('users.index')}}"
              class="rounded-xl shadow bg-gray-100 p-4">
            @csrf
            <h1 class="font-semibold text-xl text-gray-800 leading-tight">{{ __('datatable.filters') }}</h1>
            <div class="grid grid-cols-3 gap-10">
                <div class="">
                    <x-input-label
                        for="name"
                        :value="__('users.fields.name')"
                    />
                    <x-text-input
                        id="name"
                        name="name"
                        type="text"
                        :value="$filter->name ?? __('')"
                        class="mt-1 block w-full"
                    />
                </div>
                <div class="">
                    <x-input-label
                        for="email"
                        :value="__('users.fields.email')"
                    />
                    <x-text-input
                        id="email"
                        name="email"
                        type="text"
                        :value="$filter->email ?? __('')"
                        class="mt-1 block w-full"
                    />
                </div>
                <div class="">
                    <x-input-label
                        for="is_active"
                    >
                        {{ __('users.statuses.success') }}
                        <x-checkbox
                            id="is_active"
                            name="is_active"
                            value="1"
                            :checked="$filter->is_active"
                        />
                    </x-input-label>
                </div>
            </div>
            <h1 class="font-semibold text-xl text-gray-800 leading-tight my-2">{{__('datatable.sorting')}}</h1>
            <div class="grid grid-cols-5 gap-10">
                <div>
                    <x-input-label
                        for="order_name"
                        :value="__('users.fields.name')"
                    />
                    <x-select
                        id="order_name"
                        name="order_name"
                        class="mt-1"
                        :data="$order->default"
                        :selected="$order->name ?? 0"
                    />
                </div>
                <div>
                    <x-input-label
                        for="order_email"
                        :value="__('users.fields.email')"
                    />
                    <x-select
                        id="order_email"
                        name="order_email"
                        class="mt-1"
                        :data="$order->default"
                        :selected="$order->email ?? 0"
                    />
                </div>
            </div>
            <div
                class="flex items-center gap-4 mt-4"
            >
                <x-primary-button>
                    {{ __('actions.apply') }}
                </x-primary-button>
            </div>
        </form>
        <table class="table-auto w-full my-5">
            <tr>
                <th class="w-1/12 border-2 border-gray-400 px-4 py-2">№</th>
                <th class="w-4/12 border-2 border-gray-400 px-4 py-2">{{__('users.fields.name')}}</th>
                <th class="w-1/12 border-2 border-gray-400 px-4 py-2">{{__('users.fields.email')}}</th>
                <th class="w-1/12 border-2 border-gray-400 px-4 py-2">{{__('users.fields.status')}}</th>
                <th class="w-1/12 border-2 border-gray-400 px-4 py-2">{{__('roles.headers.title')}}</th>
                <th class="w-4/12 border-2 border-gray-400 px-4 py-2">{{__('datatable.action')}}</th>
            </tr>
            @if(!empty($data->items()))
                @php $pageCount = ($data->currentPage() * $data->perPage()) - $data->perPage(); @endphp
                @foreach ($data as $key => $user)
                    <tr>
                        <td class="border-2 border-gray-400 px-4 py-2">{{ ++$key + $pageCount }}</td>
                        <td class="border-2 border-gray-400 px-4 py-2">{{ $user->name}}</td>
                        <td class="border-2 border-gray-400 px-4 py-2">{{ $user->email }}</td>
                        <td class="border-2 border-gray-400 px-4 py-2">
                            @if($user->is_active)
                                <x-badge body="green">{{ __('users.statuses.success') }}</x-badge>
                            @else
                                <x-badge body="red">{{ __('users.statuses.delete') }}</x-badge>
                            @endif
                        </td>
                        <td class="border-2 border-gray-400 px-4 py-2">
                            @if(!empty($user->getRoleNames()))
                                @foreach($user->getRoleNames() as $roleName)
                                    <x-badge body="green">{{ $roleName }}</x-badge>
                                @endforeach
                            @endif
                        </td>
                        <td class="border-2 border-gray-400 px-4 py-2">
                            <x-a
                                body="info"
                                href="{{ route('users.show',$user->id) }}"
                            >{{__('actions.view')}}
                            </x-a>
                            @can('users_delete')
                                @if($user->is_active)
                                    <x-a href="{{ route('users.edit',$user->id) }}">&#128393;</x-a>
                                    <form
                                        action="{{ route('users.destroy', $user->id) }}"
                                        method="POST"
                                        style="display:inline"
                                    >
                                        @csrf
                                        @method('DELETE')
                                        <x-btn
                                            body="danger"
                                            type="submit"
                                        >&times;
                                        </x-btn>
                                    </form>
                                @endif
                            @endcan
                        </td>
                    </tr>
                @endforeach
            @else
                <tr>
                    <td colspan="6"><x-no-data></x-no-data></td>
                </tr>
            @endif
        </table>
        <x-paginate :paginator="$data"></x-paginate>
    </div>
</x-app-layout>

resources/views/users/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="mb-5">
            <div class="float-left">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight ">{{ __('users.headers.view') }}</h2>
            </div>
            <div class="float-right">
                <x-a href="{{ route('users.index') }}">{{ __('actions.back') }}</x-a>
            </div>
        </div>
    </x-slot>
    <div class="container mx-auto my-5 bg-gray-50 rounded">
        @if ($message = Session::get('success'))
            <div class="w-full px-10 py-5 bg-green-500">
                <p>{{ $message }}</p>
            </div>
        @endif
        <div class="py-5 mx-5">
            <div class="flex flex-col">
                <strong>{{ __('users.fields.name') }}:</strong>
                {{ $user->name}}
            </div>
            <div class="flex flex-col">
                <strong>{{ __('users.fields.email') }}:</strong>
                {{ $user->email }}
            </div>
            <div class="flex flex-col">
                <strong>{{ __('users.fields.email_verified') }}:</strong>
                {{ \Carbon\Carbon::parse($user->email_verified_at)->format('d.m.Y H:i:s') }}
            </div>
            <div class="my-3">
                <strong>{{ __('roles.headers.title') }}:</strong>
                @if(!empty($user->getRoleNames()))
                    @foreach($user->getRoleNames() as $roleName)
                        <x-badge body="green">{{ $roleName }}</x-badge>
                    @endforeach
                @endif
            </div>
            @if(!$user->is_active)
                @can('users_edit')
                    <div class="my-3">
                        <form method="POST" action="{{route('users.recovery', $user->id)}}">
                            @csrf
                            @method('PATCH')
                            <x-primary-button>{{ __('actions.recovery') }}</x-primary-button>
                        </form>
                    </div>
                @endcan
            @endif
        </div>
        <x-history-table :history="$history"></x-history-table>
    </div>
</x-app-layout>