routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\WelcomeController;
use App\Http\Middleware\JWTValidation;
use App\Http\Middleware\UserAuthorizationValidation;
use App\Http\Modules\Auth\AuthController;
use App\Http\Modules\Authors\AuthorsController;
use App\Http\Modules\Basket\BasketController;
use App\Http\Modules\Files\FilesController;
use App\Http\Modules\Genres\GenresController;
use App\Http\Modules\News\NewsController;
use App\Http\Modules\Orders\OrdersController;
use App\Http\Modules\Products\ProductsController;
use App\Http\Modules\Publishers\PublishersController;
use App\Http\Modules\Roles\RolesController;
use App\Http\Modules\Users\UsersController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->group(function () {
    Route::get('/', function () {
       if (Auth::check()) {
           return redirect()->route('profile.edit');
       } else {
           return redirect()->route('login');
       }
    });
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->middleware(['auth', 'verified'])->name('dashboard');

    Route::middleware('auth')->group(function () {
        Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
        Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

        Route::resource('roles', RolesController::class);

        Route::resource('users', UsersController::class);
        Route::patch('/users/{id}/recovery', [UsersController::class, 'recovery'])->name('users.recovery');

        Route::resource('authors', AuthorsController::class);
        Route::patch('/authors/{id}/recovery', [AuthorsController::class, 'recovery'])->name('authors.recovery');

        Route::resource('genres', GenresController::class);
        Route::patch('/genres/{id}/recovery', [GenresController::class, 'recovery'])->name('genres.recovery');

        Route::resource('publishers', PublishersController::class);
        Route::patch('/publishers/{id}/recovery', [PublishersController::class, 'recovery'])->name('publishers.recovery');

        Route::resource('orders', OrdersController::class);
        Route::patch('/orders/{id}/recovery', [OrdersController::class, 'recovery'])->whereNumber('id')->name('orders.recovery');
        Route::post('/orders/{id}/repeat', [OrdersController::class, 'repeat'])->whereNumber('id')->name('orders.repeat');
        Route::post('/orders/{id}/cancel', [OrdersController::class, 'cancel'])->whereNumber('id')->name('orders.cancel');

        Route::resource('files', FilesController::class);
        Route::patch('/files/{id}/recovery', [FilesController::class, 'recovery'])->name('files.recovery');
        // PRODUCTS
        Route::get('/products', [ProductsController::class, 'adminIndex'])->name('products.admin.index');
        Route::get('/products/{id}', [ProductsController::class, 'adminShow'])->whereNumber('id')->name('products.admin.show');
        Route::get('/products/{id}/edit', [ProductsController::class, 'adminEdit'])->whereNumber('id')->name('products.admin.edit');
        Route::get('/products/create', [ProductsController::class, 'adminCreate'])->name('products.admin.create');
        Route::post('/products', [ProductsController::class, 'adminStore'])->name('products.admin.store');
        Route::patch('/products/{id}', [ProductsController::class, 'adminUpdate'])->whereNumber('id')->name('products.admin.update');
        Route::delete('/products/{id}', [ProductsController::class, 'adminDestroy'])->whereNumber('id')->name('products.admin.destroy');
        Route::patch('/products/{id}/recovery', [ProductsController::class, 'adminRecovery'])->whereNumber('id')->name('products.admin.recovery');
        // NEWS
        Route::get('/news', [NewsController::class, 'adminIndex'])->name('news.admin.index');
        Route::get('/news/{id}', [NewsController::class, 'adminShow'])->whereNumber('id')->name('news.admin.show');
        Route::get('/news/{id}/edit', [NewsController::class, 'adminEdit'])->whereNumber('id')->name('news.admin.edit');
        Route::get('/news/create', [NewsController::class, 'adminCreate'])->name('news.admin.create');
        Route::post('/news', [NewsController::class, 'adminStore'])->name('news.admin.store');
        Route::patch('/news/{id}', [NewsController::class, 'adminUpdate'])->whereNumber('id')->name('news.admin.update');
        Route::delete('/news/{id}', [NewsController::class, 'adminDestroy'])->whereNumber('id')->name('news.admin.destroy');
        Route::patch('/news/{id}/recovery', [NewsController::class, 'adminRecovery'])->whereNumber('id')->name('news.admin.recovery');
    });

    require __DIR__.'/auth.php';
});

Route::prefix('api')->group(function () {
    Route::post('/login', [AuthController::class, 'login']);
    Route::post('/registration', [AuthController::class, 'registration']);
    Route::middleware([
        JWTValidation::class,
        UserAuthorizationValidation::class
    ])->group(function () {
        Route::get('/user', [AuthController::class, 'getCurrentUser']);
        Route::post('/logout', [AuthController::class, 'logout']);
        Route::post('/news', [NewsController::class, 'store']);
        Route::patch('/news/{id}', [NewsController::class, 'update'])->whereNumber('id');
        Route::delete('/news/{id}', [NewsController::class, 'destroy'])->whereNumber('id');
        Route::post('/news/{id}/recovery', [NewsController::class, 'recovery'])->name('news.recovery');
        Route::post('/products', [ProductsController::class, 'store']);
        Route::patch('/products/{id}', [ProductsController::class, 'update'])->whereNumber('id');
        Route::delete('/products/{id}', [ProductsController::class, 'destroy'])->whereNumber('id');
        Route::post('/products/{id}/recovery', [ProductsController::class, 'recovery']);
        Route::get('/basket', [BasketController::class, 'index'])->name('basket.index');
        Route::post('/products/{id}/basket', [BasketController::class, 'store'])->whereNumber('id')->name('basket.store');
        Route::patch('/basket', [BasketController::class, 'update'])->name('basket.update');
        Route::post('/basket/order', [OrdersController::class, 'storeByBasket']);
    });
    Route::get('/welcome', [WelcomeController::class, 'index']);
    Route::get('/products', [ProductsController::class, 'index']);
    Route::get('/products/{id}', [ProductsController::class, 'show'])->whereNumber('id');
    Route::get('/news', [NewsController::class, 'index']);
    Route::get('/news/{id}', [NewsController::class, 'show'])->whereNumber('id');
    Route::get('/autocomplete/authors', [AuthorsController::class, 'autocomplete']);
    Route::get('/autocomplete/genres', [GenresController::class, 'autocomplete']);
    Route::get('/autocomplete/publishers', [PublishersController::class, 'autocomplete']);
    Route::get('/autocomplete/users', [UsersController::class, 'autocomplete']);
});

app/Models/Author.php
<?php

namespace App\Models;

use App\Traits\HistoryModelTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;
use Panoscape\History\HasHistories;

class Author extends Model
{
    use HasFactory, HasHistories, HistoryModelTrait;
    protected $table = 'authors';
    protected $guarded = [];
    public $timestamps = true;

    public static function autocomplete(): Collection
    {
        return self::query()
            ->select('id as value', 'fio as label')
            ->where('status', '=', true)
            ->orderBy('fio')
            ->get();
    }

    public function getModelLabel()
    {
        return $this->fio;
    }

    public function historyMetaFields(): array
    {
        return [
            'fio' => [
                'name' => 'ФИО',
            ],
            'status' => [
                'name' => 'Статус',
            ],
        ];
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/authors/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="mb-5">
            <div class="float-left">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight">{{ __('authors.headers.create') }}</h2>
            </div>
            <div class="float-right">
                <x-a href="{{ route('authors.index') }}">{{ __('actions.back') }}</x-a>
            </div>
        </div>
    </x-slot>
    @if (count($errors) > 0)
        <div class="w-full px-10 py-5 bg-red-700">
            <strong>{{ __('validation.whoops') }}</strong>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="container mx-auto my-5 bg-gray-50 rounded">
        <div class="py-5 mx-5 flex flex-col justify-center items-center">
            <form action="{{route('authors.store')}}" method="POST">
                @csrf
                <div class="my-5 mx-5">
                    <div class="flex flex-col">
                        <strong>{{ __('authors.fields.fio') }}</strong>
                        <x-text-input type="text" name="fio" :placeholder="__('authors.fields.fio')"></x-text-input>
                    </div>
                    <div class="mt-2">
                        <x-btn type="submit">{{ __('actions.submit') }}</x-btn>
                    </div>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/authors/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="mb-5">
            <div class="float-left">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight">{{ __('authors.headers.update') }}</h2>
            </div>
            <div class="float-right">
                <x-a href="{{ route('authors.index') }}">{{ __('actions.back') }}</x-a>
            </div>
        </div>
    </x-slot>
    @if (count($errors) > 0)
        <div class="w-full px-10 py-5 bg-red-700">
            <strong>{{ __('validation.whoops') }}</strong>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="container mx-auto my-5 bg-gray-50 rounded">
        <div class="py-5 mx-5 flex flex-col justify-center items-center">
            <form action="{{ route('authors.update', $author->id) }}" method="POST">
                @csrf
                @method('PATCH')
                <div class="my-5 mx-5">
                    <div class="flex flex-col">
                        <strong>{{ __('authors.fields.fio') }}</strong>
                        <x-text-input name="fio" type="text"
                                      :placeholder="__('authors.fields.fio')"
                                      :value="$author->fio"
                                      class="form-input rounded border-gray-300"/>
                    </div>
                    <div class="mt-2">
                        <x-btn type="submit">{{ __('actions.submit') }}</x-btn>
                    </div>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/authors/index.blade.php
<x-app-layout>

    <x-slot name="header">
        <div class="mb-5">
            <div class="float-left">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight ">{{ __('authors.headers.title') }}</h2>
            </div>
            <div class="float-right">
                @can('authors_edit')
                    <x-a body="success" href="{{ route('authors.create') }}">{{ __('authors.headers.create') }}</x-a>
                @endcan
            </div>
        </div>
    </x-slot>


@if ($message = Session::get('success'))
    <div class="w-full px-10 py-5 bg-green-500" >
        <p>{{ $message }}</p>
    </div>
@endif

<div class="container mx-auto px-4 my-5">
    <form method="GET" action="{{route('authors.index')}}"
          class="rounded-xl shadow bg-gray-100 p-4">
        @csrf
        <h1 class="font-semibold text-xl text-gray-800 leading-tight">{{ __('datatable.filters') }}</h1>
        <div class="grid grid-cols-3 gap-10">
            <div class="">
                <x-input-label
                    for="fio"
                    :value="__('authors.fields.fio')"
                />
                <x-text-input
                    id="fio"
                    name="fio"
                    type="text"
                    :value="$filter->fio ?? __('')"
                    class="mt-1 block w-full"
                />
            </div>
        </div>
        <h1 class="font-semibold text-xl text-gray-800 leading-tight my-2">{{ __('datatable.sorting') }}</h1>
        <div class="grid grid-cols-5 gap-10">
            <div>
                <x-input-label
                    for="order_fio"
                    :value="__('authors.fields.fio')"
                />
                <x-select
                    id="order_fio"
                    name="order_fio"
                    class="mt-1"
                    :data="$order->default"
                    :selected="$order->fio ?? 0"
                />
            </div>
        </div>
        <div
            class="flex items-center gap-4 mt-4"
        >
            <x-primary-button>
                {{ __('actions.apply') }}
            </x-primary-button>
        </div>
    </form>
    <table class="table-auto w-full my-5">
        <thead>
        <tr>
            <th class="w-1/12 border-2 border-gray-400 px-4 py-2">№</th>
            <th class="w-4/12 border-2 border-gray-400 px-4 py-2">{{ __('authors.fields.fio') }}</th>
            <th class="w-2/12 border-2 border-gray-400 px-4 py-2">{{__('authors.fields.status')}}</th>
            <th class="w-4/12 border-2 border-gray-400 px-4 py-2">{{ __('datatable.action') }}</th>
        </tr>
        </thead>
        <tbody>
        @if(!empty($authors->items()))
            @php $pageCount = ($authors->currentPage() * $authors->perPage()) - $authors->perPage(); @endphp
            @foreach ($authors as $key => $author)
                <tr>
                    <td class="border-2 border-gray-400 px-4 py-2">{{ ++$key + $pageCount }}</td>
                    <td class="border-2 border-gray-400 px-4 py-2">{{ $author->fio }}</td>
                    <td class="border-2 border-gray-400 px-4 py-2">
                        @if($author->status)
                            <x-badge body="green">{{ __('authors.statuses.success') }}</x-badge>
                        @else
                            <x-badge body="red">{{ __('authors.statuses.delete') }}</x-badge>
                        @endif
                    </td>
                    <td class="border-2 border-gray-400 px-4 py-2">
                        <x-a body="info" href="{{ route('authors.show', $author->id) }}">{{ __('actions.view') }}</x-a>
                        @can('authors_edit')
                            @if($author->status)
                                <x-a  href="{{ route('authors.edit', $author->id) }}">&#128393;</x-a>
                                <form action="{{ route('authors.destroy', $author->id) }}" method="POST" class="inline-block">
                                    @csrf
                                    @method('DELETE')
                                    <x-btn body="danger" type="submit">&times;</x-btn>
                                </form>
                            @endif
                        @endcan
                    </td>
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="4"><x-no-data></x-no-data></td>
            </tr>
        @endif
        </tbody>
    </table>
    <x-paginate :paginator="$authors"></x-paginate>
</div>
</x-app-layout>

resources/views/authors/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="mb-5">
            <div class="float-left">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight ">{{ __('authors.headers.view') }}</h2>
            </div>
            <div class="float-right">
                <x-a href="{{ route('authors.index') }}">{{ __('actions.back') }}</x-a>
            </div>
        </div>
    </x-slot>
    <div class="container mx-auto my-5 bg-gray-50 rounded flex flex-col justify-center items-center">
        @if ($message = Session::get('success'))
            <div class="w-full px-10 py-5 bg-green-500">
                <p>{{ $message }}</p>
            </div>
        @endif
        <div class="py-5 mx-5">
            <div class="flex flex-col">
                <strong>{{ __('authors.fields.fio') }}</strong>
                {{ $author->fio }}
            </div>
            @if(!$author->status)
                @can('authors_edit')
                    <div class="my-3">
                        <form method="POST" action="{{route('authors.recovery', $author->id)}}">
                            @csrf
                            @method('PATCH')
                            <x-primary-button>{{ __('actions.recovery') }}</x-primary-button>
                        </form>
                    </div>
                @endcan
            @endif
        </div>
        <x-history-table :history="$history"></x-history-table>
    </div>
</x-app-layout>